### ISSUE TITLE
36-1 with cam routine has extra missing tooth on revolution 2 - tooth 35

### ISSUE THREAD

**Issue by mike501** [speeduino/Ardu-Stim#11]
36-1 pattern should only have missing teeth at location 36 on the trigger wheel. On the second revolution (the one without the cam) tooth 35 is also missing on pattern  const unsigned char thirty_six_minus_one_with_second_trigger[] PROGMEM = 

Line reads, "     1,0,1,0,1,0,1,0,0,0, /* Teeth 31-35 */"

When it should read "     1,0,1,0,1,0,1,0,1,0, /* Teeth 31-35 */"

**Comment by DonPasquale** [comment]
Fixed:  283f72929110f0a4e3d94c3840f325f73b9fbbb8 ?

**Comment by mike501** [comment]
Yes, issue fixed.
