### ISSUE TITLE
The node stuff won't build

### ISSUE THREAD

**Issue by correa** [speeduino/Ardu-Stim#31]
fails with 'v8.h': No such file or directory while compiling some serialport.cpp

**Comment by noisymime** [comment]
Just tried a clean build here and everything compiled up OK. 

Will need to know the exact error message you're getting.

**Comment by adbancroft** [comment]
I spent hours on this issue, chasing suggestions from google. In the end, I updated my Visual Studio Build Tools to the latest versions of VS2017 and VS2019 - that fixed it.

**Comment by noisymime** [comment]
Closing as this appears to be stable. Has likely been resolved with the update to latest node versions.
