### ISSUE TITLE
Failed to compile in Arduino IDE

### ISSUE THREAD

**Issue by HenryWait** [speeduino/Ardu-Stim#4]
storage.ino: In function ‘void saveConfig()’:
storage.ino:30:10: error: ‘class EEPROMClass’ has no member named ‘update’
storage.ino:31:10: error: ‘class EEPROMClass’ has no member named ‘update’
storage.ino:32:10: error: ‘class EEPROMClass’ has no member named ‘update’
storage.ino:36:10: error: ‘class EEPROMClass’ has no member named ‘update’
storage.ino:37:10: error: ‘class EEPROMClass’ has no member named ‘update’

**Comment by noisymime** [comment]
What version of the Arduino IDE are you using? The `EEPROM.update()` function has been there for a number of years now, but if you have a version older than they then you'll need to update the IDE.

**Comment by HenryWait** [comment]
I am using Arduino 2:1.0.5 on Debian Linux, the previous release 0.0.3 compiles fine still.

**Comment by noisymime** [comment]
That's IDE version 1.0.5, which was released in 2013. You need to update to one of the newer versions (1.8+ is recommended).

This might help: https://www.arduino.cc/en/guide/linux

**Comment by HenryWait** [comment]
Compiles perfectly now on 1.8.13
Apologies should have made sure I was using the latest version.
