### ISSUE TITLE
Firmware upload speed is fixed.

### ISSUE THREAD

**Issue by diy-efi** [speeduino/Ardu-Stim#61]
When uploading FW, speed is fixed at 57600

https://github.com/speeduino/Ardu-Stim/blob/0ed5648feb0415045ff804e57b6545304d71a672/UI/main.js#L116

Some Nanos ship with a bootloader which uses 115200

The ability to switch or autodetect this would be ideal

**Comment by noisymime** [comment]
This proved to be a LOT more difficult that it appears. I've made it so it assumes a new bootloader and watches for a fail. If it does fail it will retry for the old bootloaloder.

I cannot find any more elegant method than this of detecting the old vs new bootloaders.
