### ISSUE TITLE
Hi, how can I repackage the Ardu-Stim source as a ready-to-run binary for Windows?

### ISSUE THREAD

**Issue by Addictorator** [speeduino/Ardu-Stim#78]
I forked the ardu-stim project for a use case that requires arduino Mega 2560, and made it easier for the user to install the firmware by replacing the Nano firmware hex with one for Mega 2560 and changing the avrdude arguments to write to the Mega. It works when I install it from the source and electron-rebuild, the firmware installs successfully and the mega can be connected to, but trying to make a ready-to-run distro for Windows x64 so that the file can be run without dependencies like npm, python and git when compiling from source, hasn't worked for me so far. 

I've tried using electron forge, which gives me an executable that runs but it hangs when installing the firmware. Using the electron-packager-interactive to pack it gives me an executable that gives an error on launch, and electron-builder's compiled executable runs without errors but is unable to show the connected Mega on the list. I'm fairly inexperienced in Node.js and electron apps, so I might be doing something obvious wrong here as well. I'd like it if anyone can tell me how to package my Ardu-Stim fork into a ready-to-run for Windows x64, thanks!

**Comment by clytle374** [comment]
Please share!

**Comment by noisymime** [comment]
> Please share!

What exactly are you trying to achieve? There are Windows binaries published on the releases page or you can package it yourself with: `npm run package-win`

**Comment by clytle374** [comment]
Trying to figure how how to build it so I can try to add some changes.  Trying to add simulation for a analog MAP signal to work as a cam position sensor.  
But that'll be another topic.  I also missed that it was specific to windows, and I'm on linux

**Comment by noisymime** [comment]
It's not specific to Windows, it runs on Windows, Mac and Linux. 

Build instructions are in the Readme file

**Comment by clytle374** [comment]
I found it and figured out how to run the source too, thanks
